
package calculadora.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.4
 * Fri Dec 23 22:17:20 BRT 2022
 * Generated source version: 3.4.4
 */

@XmlRootElement(name = "multiplica", namespace = "http://calculadora/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "multiplica", namespace = "http://calculadora/", propOrder = {"arg0", "arg1"})

public class Multiplica {

    @XmlElement(name = "arg0")
    private java.lang.Double arg0;
    @XmlElement(name = "arg1")
    private java.lang.Double arg1;

    public java.lang.Double getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.Double newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.Double getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.Double newArg1)  {
        this.arg1 = newArg1;
    }

}

