package calculadora;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2022-12-23T22:45:19.066-03:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://calculadora/", name = "CalculadoraExemplo")
@XmlSeeAlso({ObjectFactory.class})
public interface CalculadoraExemplo {

    @WebMethod
    @RequestWrapper(localName = "subtrai", targetNamespace = "http://calculadora/", className = "calculadora.Subtrai")
    @ResponseWrapper(localName = "subtraiResponse", targetNamespace = "http://calculadora/", className = "calculadora.SubtraiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Double subtrai(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Double arg1
    );

    @WebMethod
    @RequestWrapper(localName = "divide", targetNamespace = "http://calculadora/", className = "calculadora.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://calculadora/", className = "calculadora.DivideResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Double divide(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Double arg1
    );

    @WebMethod
    @RequestWrapper(localName = "multiplica", targetNamespace = "http://calculadora/", className = "calculadora.Multiplica")
    @ResponseWrapper(localName = "multiplicaResponse", targetNamespace = "http://calculadora/", className = "calculadora.MultiplicaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Double multiplica(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Double arg1
    );

    @WebMethod
    @RequestWrapper(localName = "soma", targetNamespace = "http://calculadora/", className = "calculadora.Soma")
    @ResponseWrapper(localName = "somaResponse", targetNamespace = "http://calculadora/", className = "calculadora.SomaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Double soma(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Double arg1
    );
}
