package calculadora;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2022-12-23T22:45:19.072-03:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "CalculadoraExemploService",
                  wsdlLocation = "http://localhost:8080/Calculadora/services/CalculadoraExemploPort?wsdl",
                  targetNamespace = "http://calculadora/")
public class CalculadoraExemploService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://calculadora/", "CalculadoraExemploService");
    public final static QName CalculadoraExemploPort = new QName("http://calculadora/", "CalculadoraExemploPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Calculadora/services/CalculadoraExemploPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculadoraExemploService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Calculadora/services/CalculadoraExemploPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculadoraExemploService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculadoraExemploService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraExemploService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CalculadoraExemploService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculadoraExemploService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculadoraExemploService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CalculadoraExemplo
     */
    @WebEndpoint(name = "CalculadoraExemploPort")
    public CalculadoraExemplo getCalculadoraExemploPort() {
        return super.getPort(CalculadoraExemploPort, CalculadoraExemplo.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadoraExemplo
     */
    @WebEndpoint(name = "CalculadoraExemploPort")
    public CalculadoraExemplo getCalculadoraExemploPort(WebServiceFeature... features) {
        return super.getPort(CalculadoraExemploPort, CalculadoraExemplo.class, features);
    }

}
