
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package calculadora;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2022-12-23T22:45:19.053-03:00
 * Generated source version: 3.4.4
 *
 */

@javax.jws.WebService(
                      serviceName = "CalculadoraExemploService",
                      portName = "CalculadoraExemploPort",
                      targetNamespace = "http://calculadora/",
                      wsdlLocation = "http://localhost:8080/Calculadora/services/CalculadoraExemploPort?wsdl",
                      endpointInterface = "calculadora.CalculadoraExemplo")

public class CalculadoraExemploPortImpl implements CalculadoraExemplo {

    private static final Logger LOG = Logger.getLogger(CalculadoraExemploPortImpl.class.getName());

    /* (non-Javadoc)
     * @see calculadora.CalculadoraExemplo#subtrai(java.lang.Double arg0, java.lang.Double arg1)*
     */
    public java.lang.Double subtrai(java.lang.Double arg0, java.lang.Double arg1) {
        LOG.info("Executing operation subtrai");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.Double _return = Double.valueOf(0.9404608569701443);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see calculadora.CalculadoraExemplo#divide(java.lang.Double arg0, java.lang.Double arg1)*
     */
    public java.lang.Double divide(java.lang.Double arg0, java.lang.Double arg1) {
        LOG.info("Executing operation divide");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.Double _return = Double.valueOf(0.987198742235554);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see calculadora.CalculadoraExemplo#multiplica(java.lang.Double arg0, java.lang.Double arg1)*
     */
    public java.lang.Double multiplica(java.lang.Double arg0, java.lang.Double arg1) {
        LOG.info("Executing operation multiplica");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.Double _return = Double.valueOf(0.31860189482348766);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see calculadora.CalculadoraExemplo#soma(java.lang.Double arg0, java.lang.Double arg1)*
     */
    public java.lang.Double soma(java.lang.Double arg0, java.lang.Double arg1) {
        LOG.info("Executing operation soma");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.Double _return = Double.valueOf(0.26910022613482254);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
